name: Build and Deploy
on:
  workflow_dispatch:

  push:
    branches:
      - master

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Update Browser List ⬆️
        run: |
          npx update-browserslist-db@latest

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: dist
          branch: gh-pages
